version: '3.7'

services:
  db:
    image: postgres:15.2
    container_name: db-authtutorial
    restart: always
    environment:
      POSTGRES_DB: authtutorial
      POSTGRES_USER: franmerlini
      POSTGRES_PASSWORD: kenzito
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
