version: '3.7'

services:
  db:
    image: postgres:15.2
    container_name: auth-tutorial
    restart: always
    environment:
      POSTGRES_DB: auth-tutorial
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - 5432:5432
